use_frameworks!

target 'RNPodTestDemo_Example' do
  pod 'RNPodTestDemo', :path => '../'

  target 'RNPodTestDemo_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
